### ISSUE TITLE
Support insecure_registry option of docker-py

### ISSUE THREAD

**Issue by jeremyeder** [rhatdan/atom#4]
https://github.com/LTD-Beget/ansible-modules-core/commit/1c3f750d6865bc66617e15ca76e2ae67d6e1c09e

```
# atomic run docker-registry....com/vpavlin/rheltools df
Traceback (most recent call last):
  File "/usr/bin/atomic", line 337, in <module>
    sys.exit(args.func())
  File "/usr/bin/atomic", line 144, in run
    self.d.pull(self.image, stream=True)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 824, in pull
    repository, insecure=insecure_registry
  File "/usr/lib/python2.7/site-packages/docker/auth/auth.py", line 67, in resolve_repository_name
    return expand_registry_url(parts[0], insecure), parts[1]
  File "/usr/lib/python2.7/site-packages/docker/auth/auth.py", line 46, in expand_registry_url
    "HTTPS endpoint unresponsive and insecure mode isn't enabled."
docker.errors.DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.
```

**Comment by rhatdan** [comment]
Switching code to just use docker pull rather then docker.py for this.  Since docker pull has output.

**Comment by jeremyeder** [comment]
Thanks, that works now.

```
-bash-4.2# ./atomic run -n test docker-registry.usersys.redhat.com/vpavlin/rheltools bash
Pulling repository docker-registry.usersys.redhat.com/vpavlin/rheltools
94bcddfdb384: Download complete 
Status: Downloaded newer image for docker-registry.usersys.redhat.com/vpavlin/rheltools:latest
/usr/bin/docker run -t -i --rm --name test docker-registry.usersys.redhat.com/vpavlin/rheltools bash
bash-4.2# 
```
