### ISSUE TITLE
atomic run sometimes doesn't pull image

### ISSUE THREAD

**Issue by jeremyeder** [rhatdan/atom#5]
I am not sure what's causing this, but it is repeatable and it's not a connectivity thing.

Clean slate:
```
# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
```

First try:
```
# atomic run busybox sh
Traceback (most recent call last):
  File "/usr/bin/atomic", line 337, in <module>
    sys.exit(args.func())
  File "/usr/bin/atomic", line 145, in run
    inspect = self.d.inspect_image(self.image)["Config"]
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 709, in inspect_image
    True
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 98, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 94, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("No such image: busybox")
```

Second try:
```
# atomic run busybox sh
Traceback (most recent call last):
  File "/usr/bin/atomic", line 337, in <module>
    sys.exit(args.func())
  File "/usr/bin/atomic", line 145, in run
    inspect = self.d.inspect_image(self.image)["Config"]
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 709, in inspect_image
    True
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 98, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 94, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("No such image: busybox")
```
Third try:
```
# atomic run busybox sh
/usr/bin/docker run -t -i --rm -e CONFDIR=${CONFDIR} -e LOGDIR=${LOGDIR} -e DATADIR=${DATADIR} --name busybox busybox sh
/ # exit
```

Always seems to take 3 tries...

**Comment by rhatdan** [comment]
I think this is fixed in the latest atomic packages.

**Comment by jeremyeder** [comment]
I haven't seen this since.
